apiVersion: apps/v1
kind: Deployment
metadata:
  name: emotional-solutions
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emotional-solutions
  template:
    metadata:
      labels:
        app: emotional-solutions
    spec:
      containers:
      - name: emotional-solutions
        image: emotional-solutions:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: emotional-solutions
spec:
  selector:
    app: emotional-solutions
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
