version: '3.8'

services:
  app:
    build: .
    container_name: emotionalsolutions
    ports:
      - "5500:5500"
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql+mysqlconnector://juan:password@mysql:3306/emotion_analysis_db?charset=utf8mb4&collation=utf8mb4_general_ci
    volumes:
      - ./static/uploads:/app/static/uploads  

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: emotion_analysis_db
      MYSQL_USER: juan
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  

  client:
    build:
      context: ./client
      dockerfile: Dockerfile  # Optional, if you have a Dockerfile in 'client' folder
    container_name: client
    ports:
      - "3000:80"  # Nginx default port for serving React
    depends_on:
      - app
    environment:
      - REACT_APP_API_URL=http://app:5500

volumes:
  mysql_data:
