version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: facial_emotion_app
    env_file:
      - .env  
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5000

volumes:
  mysql_data:
